### PR TITLE
[URP] switching to deferred rendering path

### PR DESCRIPTION
**Pull request by GabFrancon**
- This PR makes all the URP assets use the deferred rendering path, as most of the static objects composing will be opaque.
- Also it seems the URP package was not correctly included in the `manifest.json` and `package-lock.json` files. Re-triggering the install of the package fixed it, now URP-based shaders work as expected.

### CODE REVIEW

**Comment by andersblomqvist** [comment]
I'm having an issue with all the materials, everything is pink.

**Comment by GabFrancon** [comment]
Yes that's because at the moment all the materials are not URP compatible, but I planned to add a default one before merging this PR. I'm also close to get the splat cube shader working for URP, but this will come in a dedicated PR.

**Review by andersblomqvist — CHANGES_REQUESTED** [review]
Then this wont be merged until that is fixed

**Comment by GabFrancon** [comment]
@andersblomqvist This should be fixed by this commit https://github.com/davidasberg/cubes_traveller/pull/13/commits/77e2e85bcbc7f9bfad13ccbd4ac08a1d4a623b4b

**Review by andersblomqvist — APPROVED** [review]
Now it looks better! Good work 👍

**Pull request merged**
