### PR TITLE
Improved host menu

### PR DESCRIPTION
**Pull request by davidasberg**
The new host menu has a dialog for choosing host name, a cancel button, and fades to the new scene in a smoother way.

https://github.com/davidasberg/cubes_traveller/assets/47108520/c64872c5-1c9d-4fb0-a8db-fa47fe8fdf7d

### CODE REVIEW

**Comment by andersblomqvist** [comment]
Looks very good, one minor issue when testing was a blank image in the middle in host menu scene. Not sure if network manager really needs a canvas and this image.

Skärmbild 2023-09-28 145344

**Comment by davidasberg** [comment]
> Looks very good, one minor issue when testing was a blank image in the middle in host menu scene. Not sure if network manager really needs a canvas and this image.
> 
> Skärmbild 2023-09-28 145344

That's strange, the image is responsible for the fading. I'll fix it as soon as I can.

**Comment by davidasberg** [comment]
> > Looks very good, one minor issue when testing was a blank image in the middle in host menu scene. Not sure if network manager really needs a canvas and this image.
> > Skärmbild 2023-09-28 145344
> 
> That's strange, the image is responsible for the fading. I'll fix it as soon as I can.

Fixed it!

**Comment by andersblomqvist** [comment]
Great stuff, nice work! 👍

**Pull request merged**
